# Generated by Django 5.2.6 on 2025-11-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQPaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("descripcion", models.TextField(blank=True)),
                ("adjunto", models.FileField(blank=True, null=True, upload_to="faq/")),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pasos",
                        to="faq.faq",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
