# Generated by Django 5.2.6 on 2025-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_faqpaso"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqpaso",
            name="titulo",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
