# Generated by Django 5.2.6 on 2025-11-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_faqpaso_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="categoria",
            field=models.CharField(
                blank=True, default="General", max_length=50, verbose_name="Categoría"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="respuesta",
            field=models.TextField(blank=True, verbose_name="Respuesta"),
        ),
    ]
