# Generated by Django 5.2.7 on 2025-10-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area_funcional',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('rrhh', 'Recursos Humanos (RRHH)'), ('ventas', 'Ventas'), ('marketing', 'Marketing'), ('produccion', 'Producción/Operaciones'), ('ti', 'Tecnología de la Información (TI)'), ('general', 'General/Administración')], default='general', max_length=20, verbose_name='Área Solicitante'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_ticket',
            field=models.CharField(choices=[('incidencia', 'Incidencia'), ('solicitud', 'Solicitud')], default='incidencia', max_length=20, verbose_name='Tipo de Ticket'),
        ),
    ]
