# Generated by Django 5.2.6 on 2025-11-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soporte", "0007_prioridad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slacalculo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="slaregla",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
