# Generated by Django 5.2.8 on 2025-11-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0010_tickethistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tickethistory',
            new_name='soporte_tic_ticket__6c9bb4_idx',
            old_name='tickethisto_ticket__4ae4a0_idx',
        ),
        migrations.RenameIndex(
            model_name='tickethistory',
            new_name='soporte_tic_ticket__f43e9f_idx',
            old_name='tickethisto_ticket__e19d2d_idx',
        ),
    ]
