# Generated by Django 5.2.8 on 2025-01-29 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soporte", "0015_perfilusuario_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjunto",
            name="archivo",
            field=models.FileField(
                upload_to="adjuntos_tickets/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"],
                        message="Solo se permiten archivos JPG, JPEG o PNG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="adjunto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="adjuntos_comentarios/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"],
                        message="Solo se permiten archivos JPG, JPEG o PNG.",
                    )
                ],
            ),
        ),
    ]
